[package]
name = "cedra_fa"
version = "1.0.0"
authors = []

[addresses]
CedraFungible = "_"

[dev-addresses]

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", subdir = "aptos-framework", rev = "mainnet" }

[dev-dependencies]
