[package]
name = "referral"
version = "1.0.0"
authors = []

[addresses]
referral_example = "_"

[dev-addresses]
referral_example = "0x45d869282e5605c700c8f153c80770b5dc9af2beadc3a35aa1c03aabff25f41c"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
