name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-move-packages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Install Cedra CLI (Ubuntu)
        run: |
          if ! command -v cedra >/dev/null 2>&1; then
            sudo add-apt-repository -y ppa:cedra-network/deps
            sudo apt-get update -y
            sudo apt-get install -y cedra-cli
          fi
          cedra --version

      - name: Make test runner executable
        run: chmod +x scripts/tests.sh

      - name: Run Move tests
        run: scripts/tests.sh

